spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:torneos
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
server:
  port: 8090
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG